CREATE TABLE IF NOT EXISTS USER (
  ID INT NOT NULL AUTO_INCREMENT,
  USER_NAME VARCHAR(100),
  PASSWORD VARCHAR(100),
  SALT INT,
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS GAME (
  ID INT NOT NULL AUTO_INCREMENT,
  START_TIME INT,
  DURATION INT,
  LAST_UPDATE INT,
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PLAYER (
  ID INT NOT NULL AUTO_INCREMENT,
  USER_ID INT NOT NULL,
  GAME_ID INT NOT NULL,
  MONEY INT,
  SCORE INT,
  LAST_UPDATE INT,
  FOREIGN KEY (USER_ID) REFERENCES USER(ID) ON DELETE CASCADE,
  FOREIGN KEY (GAME_ID) REFERENCES GAME(ID) ON DELETE CASCADE,
  COLOR VARCHAR(20),
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS RECT_BLOCK (
  ID INT NOT NULL AUTO_INCREMENT,
  PLAYER_ID INT NOT NULL,
  GAME_ID INT NOT NULL,
  X INT,
  Y INT,
  WIDTH INT,
  HEIGHT INT,
  FOREIGN KEY (GAME_ID) REFERENCES GAME(ID) ON DELETE CASCADE,
  FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER(ID) ON DELETE CASCADE,
  PRIMARY KEY (ID)
);